### ISSUE TITLE
how to add own geometry file to pulse

### ISSUE THREAD

**Issue by jingbinzhao415** [finsberg/pulse#20]
Good evening Dr. Finsberg,

I am trying to use my own geometry and h5.file. However, it doesn't work when I add the line as below:
![image](https://user-images.githubusercontent.com/93218388/140438466-af25777d-3d23-42fb-ba81-92747128f8a5.png)

The error is: 
![image](https://user-images.githubusercontent.com/93218388/140438751-62f8b906-4faa-4667-ba59-ab9aca517621.png)

I also copied my file to the folder:  pulse-master\pulse\example_meshes 
Your assistance will be really appreciated!

Thank you,
Jingbin

**Comment by finsberg** [comment]
This is because the meshes are installed as a part of the package. 

This is not really the way you should do it if you want to use your own mesh. You should not change any code inside the `pulse` library unless you want to fix a bug or add a feature. You should use it like you use any other package that you install (i.e through its API). 

 If you want to use your own mesh, then you should just put it together with the code and use the full path to the file.

**Comment by jingbinzhao415** [comment]
Hi Dr. Finsberg,

Thank you so much for your reply and information.

Best regards,
Jingbin
